//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharityOrganization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisation
    {
        public string OrganisationName { get; set; }
        public string OrganisationStreetNo { get; set; }
        public string OrganisationCity { get; set; }
        public string OrganisationState { get; set; }
        public string OrganisationZipCode { get; set; }
    }
}
